server:
  port: 8081
  servlet:
    context-path: /lifecare
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
    
    
    
    
spring:
#  datasource:
#    name: dev
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lifecare-dev?useUnicode=true&useSSL=false
#    username: root
#    password: guojian
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 9999MB
      max-file-size: 9999MB
      max-request-size: 9999MB
  druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lifecare-dev?useUnicode=true&useSSL=false
    username: root
    password: buzhidao
    
    max-active: 30
    min-idle: 5
    max-wait: 10000
    validation-query: SELECT 'x'
mybatis:
  mapper-locations:
  - classpath:mappers/cn/com/dbridge/lifecare/dao/mapper/*.xml
  pagehelper: null
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

storage: 
  location: ../../uploads
  showPath: http://localhost:8081/lifecare/api/file/files/