server:
  port: 8080
  servlet:
    context-path: /jtrain
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    name: dev
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://210.76.163.54:3306/jtrain-test?characterEncoding=utf-8&useSSL=false
    username: root
    password: Win2012@djbsql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    filters: stat
    maxWait: 60000
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 9999MB
      max-file-size: 9999MB
      max-request-size: 9999MB
mybatis:
  mapper-locations:
  - classpath:mappers/cn/com/dbridge/jtraining/dao/generator/mapper/*.xml
  pagehelper: null
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
websocket:
  port: 8081
storage: 
  location: ../../uploads
  
breakpoint: 
  upload:
    dir: D:\project\jtrain\uploads
    #1024*1024=1 048 576,5M=5 242 880,10M=10485760
    chunkSize: 5 242 8800  
#upload-url: http://49.1.100.1:8081  
  