package com.djb.art.model;

import java.util.Date;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.RESOURCE_ID
     *
     * @mbg.generated
     */
    private Integer resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.PARENT_ID
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.RESOURCE_NAME
     *
     * @mbg.generated
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.RESOURCE_TYPE
     *
     * @mbg.generated
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.PERMISSION
     *
     * @mbg.generated
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.ORDER
     *
     * @mbg.generated
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.STATUS
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_back_resource.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.RESOURCE_ID
     *
     * @return the value of sys_back_resource.RESOURCE_ID
     *
     * @mbg.generated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.RESOURCE_ID
     *
     * @param resourceId the value for sys_back_resource.RESOURCE_ID
     *
     * @mbg.generated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.PARENT_ID
     *
     * @return the value of sys_back_resource.PARENT_ID
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.PARENT_ID
     *
     * @param parentId the value for sys_back_resource.PARENT_ID
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.RESOURCE_NAME
     *
     * @return the value of sys_back_resource.RESOURCE_NAME
     *
     * @mbg.generated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.RESOURCE_NAME
     *
     * @param resourceName the value for sys_back_resource.RESOURCE_NAME
     *
     * @mbg.generated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.RESOURCE_TYPE
     *
     * @return the value of sys_back_resource.RESOURCE_TYPE
     *
     * @mbg.generated
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.RESOURCE_TYPE
     *
     * @param resourceType the value for sys_back_resource.RESOURCE_TYPE
     *
     * @mbg.generated
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.URL
     *
     * @return the value of sys_back_resource.URL
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.URL
     *
     * @param url the value for sys_back_resource.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.PERMISSION
     *
     * @return the value of sys_back_resource.PERMISSION
     *
     * @mbg.generated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.PERMISSION
     *
     * @param permission the value for sys_back_resource.PERMISSION
     *
     * @mbg.generated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.ORDER
     *
     * @return the value of sys_back_resource.ORDER
     *
     * @mbg.generated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.ORDER
     *
     * @param order the value for sys_back_resource.ORDER
     *
     * @mbg.generated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.STATUS
     *
     * @return the value of sys_back_resource.STATUS
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.STATUS
     *
     * @param status the value for sys_back_resource.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.CREATE_TIME
     *
     * @return the value of sys_back_resource.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.CREATE_TIME
     *
     * @param createTime the value for sys_back_resource.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_back_resource.UPDATE_TIME
     *
     * @return the value of sys_back_resource.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_back_resource.UPDATE_TIME
     *
     * @param updateTime the value for sys_back_resource.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}