package com.djb.art.repository;

import com.djb.art.model.TestResource;

public interface TestResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_test_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_test_resource
     *
     * @mbg.generated
     */
    int insert(TestResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_test_resource
     *
     * @mbg.generated
     */
    int insertSelective(TestResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_test_resource
     *
     * @mbg.generated
     */
    TestResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_test_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_test_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestResource record);
}